use std::env;
use std::ffi::{OsStr, OsString};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

const SERVICE_ENV_VARS: &[&str] = &[
    "PATH",
    "T3CODE_PAIR_ADMIN_PIN",
    "T3CODE_PORT",
    "T3CODE_PAIR_ADMIN_PORT",
    "CLIPBOARD_SCREENSHOTS_DIR",
    "XDG_CACHE_HOME",
    "XDG_CONFIG_HOME",
    "XDG_DATA_HOME",
    "XDG_STATE_HOME",
    "SSH_AUTH_SOCK",
    "GH_CONFIG_DIR",
    "GH_HOST",
    "GH_TOKEN",
    "GITHUB_TOKEN",
];

const GENERATED_HEADER: &str = "# Generated by claude-sandbox --install-service";

pub fn recorded_environment(
    lookup: impl Fn(&str) -> Option<OsString>,
) -> Result<Vec<(String, String)>, String> {
    let runtime_dir = lookup("XDG_RUNTIME_DIR").filter(|value| !value.is_empty());
    let mut environment = Vec::new();
    for name in SERVICE_ENV_VARS {
        let Some(value) = lookup(name).filter(|value| !value.is_empty()) else {
            continue;
        };
        // A forwarded agent socket dies with its login session; only one in
        // the runtime directory is still there when the service starts.
        if *name == "SSH_AUTH_SOCK"
            && !runtime_dir
                .as_ref()
                .is_some_and(|runtime_dir| Path::new(&value).starts_with(runtime_dir))
        {
            continue;
        }
        let value = value
            .into_string()
            .map_err(|_| format!("environment variable {name} is not valid UTF-8"))?;
        environment.push(((*name).to_string(), value));
    }
    Ok(environment)
}

pub struct InstallOptions {
    pub explicit_name: Option<String>,
    pub command: String,
    pub cwd: PathBuf,
    pub program: PathBuf,
    pub arguments: Vec<String>,
    pub environment: Vec<(String, String)>,
    pub config_dir: PathBuf,
}

#[derive(Debug)]
pub struct InstallOutcome {
    pub path: PathBuf,
    pub unit_name: String,
    pub command_line: String,
    pub cwd: PathBuf,
    pub environment: Vec<String>,
    pub updated: bool,
    pub reloaded: bool,
}

struct UnitSpec<'a> {
    command: &'a str,
    cwd: &'a Path,
    program: &'a Path,
    arguments: &'a [String],
    environment: &'a [(String, String)],
}

pub fn filter_install_argument(
    arguments: impl IntoIterator<Item = OsString>,
) -> Result<(Vec<String>, Option<String>), String> {
    let mut filtered = Vec::new();
    let mut install_name = None;
    let mut removed = false;

    for (index, argument) in arguments.into_iter().enumerate() {
        let argument = argument
            .into_string()
            .map_err(|_| format!("argument {index} is not valid UTF-8"))?;
        if !removed && argument == "--install-service" {
            removed = true;
            continue;
        }
        if !removed && argument.starts_with("--install-service=") {
            install_name = Some(argument["--install-service=".len()..].to_string());
            removed = true;
            continue;
        }
        filtered.push(argument);
    }

    if !removed {
        return Err("could not find --install-service in the invocation".to_string());
    }
    Ok((filtered, install_name))
}

pub fn resolve_program_path(
    invoked: &OsStr,
    cwd: &Path,
    path: Option<&OsStr>,
    fallback: &Path,
) -> PathBuf {
    if invoked.as_bytes().contains(&b'/') {
        let invoked = Path::new(invoked);
        return cwd.join(invoked).components().collect();
    }

    if let Some(path) = path {
        for directory in env::split_paths(path) {
            let directory = if directory.as_os_str().is_empty() {
                cwd.to_path_buf()
            } else if directory.is_absolute() {
                directory
            } else {
                cwd.join(directory)
            };
            let candidate = directory.join(invoked);
            if candidate
                .metadata()
                .map(|metadata| metadata.is_file() && metadata.permissions().mode() & 0o111 != 0)
                .unwrap_or(false)
            {
                return candidate;
            }
        }
    }
    fallback.to_path_buf()
}

pub fn service_config_dir(xdg_config_home: Option<&OsStr>, home: &Path) -> PathBuf {
    xdg_config_home
        .filter(|value| !value.is_empty() && Path::new(value).is_absolute())
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join(".config"))
}

pub fn derive_unit_name(
    explicit_name: Option<&str>,
    command: &str,
    cwd: &Path,
) -> Result<String, String> {
    if let Some(name) = explicit_name {
        let name = name.strip_suffix(".service").unwrap_or(name);
        if name.is_empty()
            || name.starts_with('-')
            || !name
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || "_-".contains(character))
        {
            return Err(
                "--install-service name must contain only ASCII letters, digits, '_' or '-', and not start with '-'"
                    .to_string(),
            );
        }
        return Ok(name.to_string());
    }

    Ok(format!(
        "claude-sandbox-{command}-{}",
        crate::sanitised_project_basename(cwd)
    ))
}

fn has_control(value: &str) -> bool {
    value.chars().any(char::is_control)
}

fn check_value(value: &str, item: &str) -> Result<(), String> {
    if has_control(value) {
        Err(format!("{item} contains a control character"))
    } else {
        Ok(())
    }
}

fn quote_exec_word(value: &str, escaped: String) -> String {
    if !value.is_empty()
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "-_./:=@,+".contains(character))
    {
        escaped
    } else {
        format!("\"{escaped}\"")
    }
}

fn exec_word(value: &str, item: &str) -> Result<String, String> {
    check_value(value, item)?;
    let escaped = value
        .replace('%', "%%")
        .replace('$', "$$")
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    Ok(quote_exec_word(value, escaped))
}

// systemd neither expands nor unescapes the executable path the way it does
// arguments, so the characters that would need it cannot be represented.
fn exec_program(value: &str) -> Result<String, String> {
    check_value(value, "program path")?;
    if value.contains(['$', '"', '\'', '\\']) {
        return Err(format!(
            "program path {value} contains a character systemd does not accept in an executable path"
        ));
    }
    Ok(quote_exec_word(value, value.replace('%', "%%")))
}

fn environment_assignment(name: &str, value: &str) -> Result<String, String> {
    check_value(value, &format!("environment variable {name}"))?;
    let escaped = value
        .replace('%', "%%")
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    Ok(format!("Environment=\"{name}={escaped}\""))
}

fn rest_of_line(value: &str, item: &str) -> Result<String, String> {
    check_value(value, item)?;
    Ok(value.replace('%', "%%"))
}

fn validate_working_directory(cwd: &Path) -> Result<&str, String> {
    if !cwd.is_absolute() {
        return Err("working directory is not absolute".to_string());
    }
    let cwd = cwd
        .to_str()
        .ok_or_else(|| "working directory is not valid UTF-8".to_string())?;
    check_value(cwd, "working directory")?;
    if cwd.ends_with('\\') || cwd.ends_with(char::is_whitespace) {
        return Err("working directory ends in a backslash or whitespace".to_string());
    }
    Ok(cwd)
}

fn render_unit(spec: &UnitSpec<'_>) -> Result<String, String> {
    let raw_cwd = validate_working_directory(spec.cwd)?;
    let cwd = rest_of_line(raw_cwd, "working directory")?;
    let description = rest_of_line(
        &format!("claude-sandbox {} in {raw_cwd}", spec.command),
        "description",
    )?;
    let program = spec
        .program
        .to_str()
        .ok_or_else(|| "program path is not valid UTF-8".to_string())?;
    let mut exec_start = vec![exec_program(program)?];
    for (index, argument) in spec.arguments.iter().enumerate() {
        exec_start.push(exec_word(argument, &format!("argument {index}"))?);
    }

    // The admin portal restarts T3 by stopping its container and leaving the
    // rest to the supervisor; other commands may be meant to finish.
    let restart = if spec.command == "t3code" {
        "always"
    } else {
        "on-failure"
    };

    let mut unit = format!(
        "{GENERATED_HEADER}; re-run it to regenerate.\n\
[Unit]\n\
Description={description}\n\
\n\
[Service]\n\
WorkingDirectory={cwd}\n"
    );
    for (name, value) in spec.environment {
        unit.push_str(&environment_assignment(name, value)?);
        unit.push('\n');
    }
    unit.push_str(&format!(
        "ExecStart={}\n\
Restart={restart}\n\
RestartSec=5\n\
SuccessExitStatus=143\n\
\n\
[Install]\n\
WantedBy=default.target\n",
        exec_start.join(" ")
    ));
    Ok(unit)
}

fn existing_working_directory(contents: &str) -> Option<&str> {
    contents
        .lines()
        .find_map(|line| line.strip_prefix("WorkingDirectory="))
}

fn check_replaceable(contents: &str, new_directory: &str) -> Result<(), String> {
    let existing = existing_working_directory(contents)
        .filter(|_| contents.starts_with(GENERATED_HEADER))
        .ok_or_else(|| "and was not generated by claude-sandbox".to_string())?;
    if existing != new_directory {
        return Err(format!("for {}", existing.replace("%%", "%")));
    }
    Ok(())
}

fn write_atomic(path: &Path, contents: &str) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| "service path has no parent directory".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("could not create {}: {error}", parent.display()))?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let temp = parent.join(format!(
        ".{}.tmp-{}-{nonce}",
        path.file_name().unwrap_or_default().to_string_lossy(),
        std::process::id()
    ));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temp)
            .map_err(|error| format!("could not create {}: {error}", temp.display()))?;
        file.write_all(contents.as_bytes())
            .map_err(|error| format!("could not write {}: {error}", temp.display()))?;
        file.sync_all()
            .map_err(|error| format!("could not sync {}: {error}", temp.display()))?;
        fs::rename(&temp, path)
            .map_err(|error| format!("could not replace {}: {error}", path.display()))?;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))
            .map_err(|error| format!("could not set permissions on {}: {error}", path.display()))
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}

fn install_with_reload(
    options: InstallOptions,
    reload: impl FnOnce() -> bool,
) -> Result<InstallOutcome, String> {
    let unit_name = derive_unit_name(
        options.explicit_name.as_deref(),
        &options.command,
        &options.cwd,
    )?;
    let spec = UnitSpec {
        command: &options.command,
        cwd: &options.cwd,
        program: &options.program,
        arguments: &options.arguments,
        environment: &options.environment,
    };
    let contents = render_unit(&spec)?;
    let unit_dir = options.config_dir.join("systemd/user");
    fs::create_dir_all(&unit_dir)
        .map_err(|error| format!("could not create {}: {error}", unit_dir.display()))?;
    let resolve = |path: &Path| {
        fs::canonicalize(path)
            .map_err(|error| format!("could not resolve {}: {error}", path.display()))
    };
    if resolve(&unit_dir)?.starts_with(resolve(&options.cwd)?) {
        return Err(format!(
            "{} is inside the directory mounted into the sandbox, where the agent could read and change the unit",
            unit_dir.display()
        ));
    }

    let path = unit_dir.join(format!("{unit_name}.service"));
    let updated = match fs::symlink_metadata(&path) {
        Ok(metadata) => {
            let existing = if metadata.is_file() {
                fs::read_to_string(&path)
                    .map_err(|error| format!("could not read {}: {error}", path.display()))?
            } else {
                String::new()
            };
            let cwd = rest_of_line(
                validate_working_directory(&options.cwd)?,
                "working directory",
            )?;
            check_replaceable(&existing, &cwd).map_err(|reason| {
                format!(
                    "{} already exists {reason}; choose another name with --install-service=NAME",
                    path.display()
                )
            })?;
            true
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
        Err(error) => return Err(format!("could not inspect {}: {error}", path.display())),
    };
    write_atomic(&path, &contents)?;
    let reloaded = reload();
    let mut command_line = vec![options.program.display().to_string()];
    command_line.extend(options.arguments);
    Ok(InstallOutcome {
        path,
        unit_name,
        command_line: command_line.join(" "),
        cwd: options.cwd,
        environment: options
            .environment
            .into_iter()
            .map(|(name, _)| name)
            .collect(),
        updated,
        reloaded,
    })
}

pub fn install(options: InstallOptions) -> Result<InstallOutcome, String> {
    install_with_reload(options, || {
        Command::new("systemctl")
            .args(["--user", "daemon-reload"])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|status| status.success())
            .unwrap_or(false)
    })
}

pub fn print_summary(outcome: &InstallOutcome) {
    let action = if outcome.updated {
        "Updated"
    } else {
        "Installed"
    };
    println!("{action} {}", outcome.path.display());
    println!();
    println!("  Command                 {}", outcome.command_line);
    println!("  Directory               {}", outcome.cwd.display());
    println!(
        "  Environment             {}",
        outcome.environment.join(", ")
    );
    println!();
    println!(
        "  Start it now            systemctl --user start {}",
        outcome.unit_name
    );
    println!(
        "  Start it at login       systemctl --user enable {}",
        outcome.unit_name
    );
    println!("  Start it at boot        loginctl enable-linger   (in addition to enable)");
    println!(
        "  Follow its output       journalctl --user -u {} -f",
        outcome.unit_name
    );
    println!();
    if !outcome.reloaded {
        println!("Could not reload systemd; run: systemctl --user daemon-reload");
        println!();
    }
    println!("The service was not started or enabled.");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_root(name: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "claude-sandbox-service-{name}-{}-{nonce}",
            std::process::id()
        ))
    }

    #[test]
    fn exec_words_follow_systemd_escaping_rules() {
        assert_eq!(
            exec_word("plain/path-1:=@,+", "argument").unwrap(),
            "plain/path-1:=@,+"
        );
        assert_eq!(exec_word("a b", "argument").unwrap(), "\"a b\"");
        assert_eq!(exec_word("a\"b", "argument").unwrap(), "\"a\\\"b\"");
        assert_eq!(exec_word("a\\b", "argument").unwrap(), "\"a\\\\b\"");
        assert_eq!(exec_word("%$", "argument").unwrap(), "\"%%$$\"");
        assert_eq!(exec_word("", "argument").unwrap(), "\"\"");
    }

    #[test]
    fn environment_values_use_environment_escaping() {
        assert_eq!(
            environment_assignment("VALUE", "%\"\\$").unwrap(),
            "Environment=\"VALUE=%%\\\"\\\\$\""
        );
    }

    #[test]
    fn control_characters_are_rejected() {
        assert!(exec_word("line\nfeed", "argument").is_err());
        assert!(environment_assignment("VALUE", "a\tb").is_err());
        assert!(validate_working_directory(Path::new("/tmp/a\nb")).is_err());
    }

    #[test]
    fn filtering_removes_only_the_first_install_flag() {
        let arguments = [
            "--install-service=mine",
            "t3code",
            "--install-service=inner",
        ]
        .map(OsString::from);
        let (filtered, name) = filter_install_argument(arguments).unwrap();
        assert_eq!(name.as_deref(), Some("mine"));
        assert_eq!(filtered, ["t3code", "--install-service=inner"]);
    }

    #[test]
    fn unit_names_support_derived_and_explicit_forms() {
        assert_eq!(
            derive_unit_name(None, "t3code", Path::new("/work/my project")).unwrap(),
            "claude-sandbox-t3code-my_project"
        );
        assert_eq!(
            derive_unit_name(Some("my-t3"), "t3code", Path::new("/work")).unwrap(),
            "my-t3"
        );
        assert_eq!(
            derive_unit_name(Some("my-t3.service"), "t3code", Path::new("/work")).unwrap(),
            "my-t3"
        );
        for invalid in ["bad/name", "-dash", "my.socket", ""] {
            assert!(derive_unit_name(Some(invalid), "t3code", Path::new("/work")).is_err());
        }
    }

    #[test]
    fn only_a_generated_unit_for_the_same_directory_is_replaceable() {
        let generated = format!("{GENERATED_HEADER}\n[Service]\nWorkingDirectory=/work/one\n");
        assert!(check_replaceable(&generated, "/work/one").is_ok());
        assert_eq!(
            check_replaceable(&generated, "/work/two").unwrap_err(),
            "for /work/one"
        );
        let foreign = "[Service]\nWorkingDirectory=/work/one\n";
        assert!(check_replaceable(foreign, "/work/one").is_err());
        assert!(check_replaceable("", "/work/one").is_err());
    }

    #[test]
    fn program_paths_reject_what_systemd_cannot_execute() {
        assert_eq!(
            exec_program("/opt/my tools/100%").unwrap(),
            "\"/opt/my tools/100%%\""
        );
        for invalid in ["/opt/we$ird", "/opt/it's", "/opt/back\\slash"] {
            assert!(exec_program(invalid).is_err());
        }
    }

    #[test]
    fn only_a_runtime_directory_agent_socket_is_recorded() {
        let record = |socket: &'static str| {
            recorded_environment(|name| match name {
                "XDG_RUNTIME_DIR" => Some("/run/user/1000".into()),
                "SSH_AUTH_SOCK" => Some(socket.into()),
                "T3CODE_PORT" => Some("3800".into()),
                "HOME" => Some("/home/stefan".into()),
                _ => None,
            })
            .unwrap()
        };
        let port = ("T3CODE_PORT".to_string(), "3800".to_string());
        assert_eq!(
            record("/tmp/ssh-XXXX/agent.42"),
            std::slice::from_ref(&port)
        );
        assert_eq!(
            record("/run/user/1000/keyring/ssh"),
            [
                port,
                (
                    "SSH_AUTH_SOCK".to_string(),
                    "/run/user/1000/keyring/ssh".to_string()
                )
            ]
        );
    }

    #[test]
    fn only_t3code_restarts_after_a_clean_exit() {
        let spec = UnitSpec {
            command: "run",
            cwd: Path::new("/work"),
            program: Path::new("/bin/claude-sandbox"),
            arguments: &["run".to_string(), "true".to_string()],
            environment: &[],
        };
        assert!(
            render_unit(&spec)
                .unwrap()
                .contains("\nRestart=on-failure\n")
        );
    }

    #[test]
    fn renders_complete_unit() {
        let arguments = vec!["--t3-managed-push".to_string(), "t3code".to_string()];
        let environment = vec![
            ("PATH".to_string(), "/usr/bin".to_string()),
            ("T3CODE_PAIR_ADMIN_PIN".to_string(), "123456".to_string()),
        ];
        let spec = UnitSpec {
            command: "t3code",
            cwd: Path::new("/home/stefan/projects"),
            program: Path::new("/home/stefan/bin/claude-sandbox"),
            arguments: &arguments,
            environment: &environment,
        };
        assert_eq!(
            render_unit(&spec).unwrap(),
            "# Generated by claude-sandbox --install-service; re-run it to regenerate.\n\
[Unit]\n\
Description=claude-sandbox t3code in /home/stefan/projects\n\
\n\
[Service]\n\
WorkingDirectory=/home/stefan/projects\n\
Environment=\"PATH=/usr/bin\"\n\
Environment=\"T3CODE_PAIR_ADMIN_PIN=123456\"\n\
ExecStart=/home/stefan/bin/claude-sandbox --t3-managed-push t3code\n\
Restart=always\n\
RestartSec=5\n\
SuccessExitStatus=143\n\
\n\
[Install]\n\
WantedBy=default.target\n"
        );
    }

    #[test]
    fn install_overwrites_same_directory_at_mode_0600_and_refuses_another() {
        let root = test_root("collision");
        let config = root.join("config");
        let cwd = root.join("project");
        fs::create_dir_all(&cwd).unwrap();
        let options = || InstallOptions {
            explicit_name: Some("test-unit".to_string()),
            command: "t3code".to_string(),
            cwd: cwd.clone(),
            program: PathBuf::from("/bin/true"),
            arguments: vec!["t3code".to_string()],
            environment: Vec::new(),
            config_dir: config.clone(),
        };
        let first = install_with_reload(options(), || false).unwrap();
        assert!(!first.updated);
        fs::set_permissions(&first.path, fs::Permissions::from_mode(0o644)).unwrap();
        let second = install_with_reload(options(), || false).unwrap();
        assert!(second.updated);
        assert_eq!(
            fs::metadata(&second.path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        fs::write(
            &second.path,
            format!("{GENERATED_HEADER}\n[Service]\nWorkingDirectory=/another/project\n"),
        )
        .unwrap();
        assert!(
            install_with_reload(options(), || false)
                .unwrap_err()
                .contains("/another/project")
        );
        fs::remove_dir_all(root).unwrap();
    }
}
